### PR TITLE
Add Jenkinsfile for Openencalve testing

### PR DESCRIPTION
**Pull request by oprinmarius**
Add Jenkinsfile for triggering Openenclave master branch testing

### CODE REVIEW

**Comment by oeciteam** [comment]
test

**Comment by oprinmarius** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Comment by ionutbalutoiu** [comment]
run integration testing

**Comment by oprinmarius** [comment]
run integration testing

**Review by ionutbalutoiu — APPROVED** [review]
LGTM

**Pull request merged**
